### ISSUE TITLE
Immagine non trovata

### ISSUE THREAD

**Issue by DavideVitali** [GuidoPenta/galactic-CV-guide#17]
Sono da GitHub app su iOS, provo a caricare il CV di Luke per poterlo ingrandire "tappandoci" sopra direttamente dal readme principale ma dice "Error loading image"

**Comment by GuidoPenta** [comment]
La ringraziamo per la segnalazione.
Il nostro customer care ha preso in carico il ticket che verrà gestito ASAP (come dicono al nord).

RingraziandoLa per l'attenzione, porgiamo cordiali saluti

**Comment by mateonunez** [comment]
Credo sia un problema dell'app nativa iOS nella gestione dei symlinks. Su webapp ed Android non si presenta questo problema.

**Comment by GuidoPenta** [comment]
Grazie Mateo!!
